spring:
  cloud:
    config:
      server:
        git:
          uri: http://127.0.0.1/config-server/spring-cloud-config-data.git
          username: "config--server"
          password: "glpat-cR34AQFyDrt5NHGZvcxW"