server:
    port: 5001
    servlet:
      context-path: '/config-server'

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          basedir: ./configs
          force-pull: true
          refreshRate: 60
          searchPaths: '{application}'
          clone-on-start: true

  actuator:
    endpoints:
      web:
        exposure:
          include: '*'
        base-path: /actuator

security:
  username: root
  password: s3cr3t

management:
  server:
    port: 9090


encrypt.key: ${ENCRYPTOR_KEY}

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.security: TRACE

