server:
    port: 5001
    servlet:
      context-path: '/config-server'

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          basedir: ./configs
          force-pull: true
          refreshRate: 60
          searchPaths: '{application}'
          clone-on-start: true

  actuator:
    endpoints:
      web:
        exposure:
          include: '*'
        base-path: /actuator

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details:  ALWAYS


encrypt.key: ${ENCRYPTOR_KEY}

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.security: TRACE



users:
  credentials:
    - username: root
      password: s3cr3t
      roles:
        - USER
        - ADMIN
    - username: monitoring
      password: monitoring
      roles:
        - MONITORING
    - username: operator
      password: operator
      roles:
        - OPERATOR

