server:
    port: 5001
    servlet:
      context-path: '/config-server'

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          basedir: ./configs
          force-pull: true
          refreshRate: 60
          searchPaths: '{application}'

  security:
    username: root
    password: s3cr3t

encrypt.key: ${ENCRYPTOR_KEY}

logging:
  level:
    org.zalando.logbook: TRACE